---
title: "Tidytuesday 16/11/2021"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

# get data
directors <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-23/directors.csv")
episodes <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-23/episodes.csv")
writers <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-23/writers.csv")
imdb <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-23/imdb.csv")
```

# Clean and join data

- forget directors and writers

```{r}
# add doctors
episodes <- episodes %>% 
  mutate(doctor = case_when(
    season_number == 1 ~ "Christopher Eccleston",
    season_number %in% 2:4 ~ "David Tennant",
    season_number %in% 5:7 ~ "Matt Smith",
    season_number%in% 8:10 ~ "Peter Capaldi",
    season_number %in% 11:13 ~ "Jodie Whittaker",
    TRUE ~ NA_character_
  ))

# combine data
to_plot <- episodes %>% 
  rename(rating_orig = rating, 
         season = season_number,
         ep_num = episode_number) %>% 
  left_join(imdb, by = c("ep_num", "season")) %>% 
  filter(type != "special") %>% 
  select(season, ep_num, uk_viewers, rating_orig, rating, episode_title, doctor) 
```

# Set theme and font

```{r}
library(showtext)
font_add_google("Poppins", "Poppins")
showtext_auto()
theme_set(theme_light(base_size = 18, base_family = "Poppins"))
```


# Plot

Inspired by [Cédric's evoluation of a ggplot] (https://www.cedricscherer.com/2019/05/17/the-evolution-of-a-ggplot-ep.-1/#final)


```{r}
# overall average rating
avg_rating <- 
  to_plot %>% 
  summarize(mean_rating = mean(rating, na.rm = TRUE)) %>% 
  pull(mean_rating)

# average per doctor
avg_doctor <- 
  to_plot %>% group_by(doctor) %>% 
  summarize(mean_rating  = mean(rating, na.rm = TRUE)) %>% 
  mutate(avg_rating = avg_rating)

set.seed(123)

(g <- to_plot %>%
  left_join(avg_doctor, by = "doctor") %>%
  mutate(doctor = fct_reorder(doctor, mean_rating)) %>%
  ggplot(aes(x = doctor, y = rating, color = doctor)) +
  geom_point(position = position_jitter(seed = 123, width = 0.2), size = 2, alpha = 0.15)+
  # geom_jitter(alpha = 0.15, size = 2, width = 0.3) +
  geom_hline(yintercept = avg_rating, size = 1, color = "gray60") +
  geom_segment(aes(
    x = doctor, xend = doctor,
    y = mean_rating, yend = avg_rating
  ), size = 2) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  coord_flip() +
  labs(x = NULL, y = NULL) +
  theme(
    legend.position = "none"
  )
)
```

Add the best 3 episodes

```{r}
best3 <- to_plot %>% arrange(-rating) %>% slice(1:3)

(g_text <- g + 
  annotate(
    "text", x = 4.7, y = 10,  size = 2.8, color = "gray20", lineheight = .9,
    label = "Blink",family = "Poppins"
  )+
  annotate(
    "text", x = 5.3, y = 9.5,  size = 2.8, color = "gray20", lineheight = .9,
    label = "Forest of the Dead", family = "Poppins"
  ) +
  annotate(
    "text", x = 2, y = 9.5,  size = 2.8, color = "gray20", lineheight = .9,
    label = "Heaven Sent", family = "Poppins"
  )
)

arrows <-
  tibble(
    x1 = c(4.7, 5.2, 2),
    x2 = c(4.95, 5, 2.2),
    y1 = c(9.9, 9.5, 9.5),
    y2 = c(9.8, 9.5, 9.55)
  )

(g_arrows <-
  g_text +
  geom_curve(
    data = arrows, aes(x = x1, y = y1, xend = x2, yend = y2),
    arrow = arrow(length = unit(0.08, "inch")), size = 0.5,
    color = "gray20", curvature = -0.3
  )
)
```

Colors

```{r}
tardis_colors <- c(
  "#00060b", 
  "#00203c",
  "#003b6f", "#6f8ea9",
  "#a6b8c7"
)
(g_colors <- g_arrows +
  scale_color_manual(values = tardis_colors)
)
```

Title

```{r}
(t_title <- 
  g_colors + 
  labs(title = "Dr. Who episode ratings",
       subtitle = "3 best episodes", 
      caption = "Data from {datardis} package, visualisation by Selina")+
   theme(
     plot.caption = element_text(size=11)
   ))

```

Add a Tardis

```{r}
library(png)
library(grid)
img <- readPNG(here::here("images/TARDIS_Box2.png"))
g <- rasterGrob(img, interpolate=TRUE)

qplot(1:10, 1:10, geom="blank") +
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point()
```



```{r}
to_plot2 <- episodes %>% 
  rename(rating_orig = rating, 
         season = season_number,
         ep_num = episode_number) %>% 
  left_join(imdb, by = c("ep_num", "season")) %>% 
  filter(type != "special") %>% 
  select(season, ep_num, uk_viewers, rating_orig, rating, first_aired,episode_title)
```

```{r}
to_plot2 %>% 
  ggplot(aes(x=first_aired, y=rating))+
  geom_point()+
  labs()
```


